---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: common-config
  namespace: tca
  labels:
    app: common
data:
  application-test.yml: |
    
    mybatis:
      mapper-locations: classpath:mybatis/mappers/*.xml
        
    
    # mapper-dao存放的包目录
    mybatis_dao_scann_packages: com.tca.core.mapper
