server:
  port: 10001

spring:
  application:
    name: tca-emp

  profiles:
    include: ${spring.profiles.active}

  datasource:
    url: jdbc:mysql://localhost:3306/tutorialdb
    username: star
    password: Pa$sw0rd

service:
  emp:
    url: http://127.0.0.1:10001