server:
  port: 16969
  servlet:
    context-path: /companyApi
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutorialdb
    username: root
    password: Pa$sw0rd
  devtools:
    restart:
      enabled: true
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.social.trade.entity
#  max-time: 2000

#logging:
#  file:
#    path: /project/logs/${spring.application.name}

#log:
#  response:
#    maxlen: 4096